var enemyData = [
	{"name":"Ander Herrera", "score":"0.45", "location":"13", "playtime":0},
	{"name":"Anthony Martial", "score":"0.16", "location":"1", "playtime":0},
	{"name":"Antonio Valencia", "score":"0.16", "location":"2", "playtime":0},
	{"name":"Chris Smalling", "score":"0.24", "location":"3", "playtime":0},
	{"name":"Daley Blind", "score":"0.18", "location":"4", "playtime":0},
	{"name":"David de Gea", "score":"0.11", "location":"5", "playtime":0},
	{"name":"Jesse Lingard", "score":"0.18", "location":"6", "playtime":0},
	{"name":"Juan Mata", "score":"0.12", "location":"12", "playtime":0},
	{"name":"Marcus Rashford", "score":"0.11", "location":"7", "playtime":0},
	{"name":"Marcos Rojo", "score":"0.14", "location":"8", "playtime":0},
	{"name":"Marouane Fellaini", "score":"0.29", "location":"9", "playtime":0},
	{"name":"Memphis Depay", "score":"0.38", "location":"14", "playtime":0},
	{"name":"Michel Carrick", "score":"0.13", "location":"10", "playtime":0},
	{"name":"Wayne Rooney", "score":"0.27", "location":"11", "playtime":0},
]